version: "3.9"

services:
    django:
        build:
            context: backend
            dockerfile: Dockerfile
        # command: sleep infinity
        command: sh -c "python3 backend/manage.py makemigrations && python3 backend/manage.py migrate && python3 backend/manage.py runserver 0.0.0.0:4000"
        volumes:
            - .:/code
        container_name: backend
        depends_on:
            - db
        network_mode: service:db
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            POSTGRES_HOST: db

    frontend:
        restart: always
        build:
            context: frontend
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        command: npm run dev --prefix frontend
        ports:
            - "3000:3000"

    db:
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
            - "4000:4000"
        volumes:
            # - postgres_data:/var/lib/postgresql/data
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            # POSTGRES_HOST_AUTH_METHOD: trust

volumes:
    postgres_data:


