version: "3.9"

services:
    django:
        build:
            context: backend
            dockerfile: Dockerfile
        working_dir: /code/backend/
        command: >
            sh -c "python3 manage.py makemigrations 
            && python3 manage.py migrate 
            && python manage.py loaddata fixtures/initial_users 
            && python manage.py loaddata fixtures/initial_menu_images
            && python3 manage.py runserver 0.0.0.0:4000"
        ports:
            - "4000:4000"
        volumes:
            - .:/code
        container_name: backend
        depends_on:
            db:
                condition: service_healthy
        restart: always
        env_file:
            - .env

    frontend:
        restart: always
        build:
            context: frontend
            dockerfile: Dockerfile
        container_name: frontend
        env_file:
            - .env
        command: sh -c "npm run $NPM_COMMAND || npm run start"
        ports:
            - "3000:3000"

    db:
        image: postgres:13
        restart: always
        container_name: db
        ports:
            - "5432:5432"
        volumes:
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U django_postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    nginx:
        restart: always
        build:
            context: nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - "80:80"
        command: ["nginx", "-g", "daemon off;"]
        depends_on:
            - django
            - frontend

volumes:
    postgres_data: