version: "3.9"

services:
    django:
        build:
            context: backend
            dockerfile: Dockerfile
        working_dir: /code/backend/
        # command: sleep infinity
        # while [ "$(pg_isready -q -h 127.0.0.1 && echo OK)"!="OK" ]; do sleep 1; done;
        command: >
            sh -c "python3 manage.py makemigrations 
            && python3 manage.py migrate 
            && python manage.py loaddata fixtures/initial_users 
            && python manage.py loaddata fixtures/initial_menu_images
            && python3 manage.py runserver 0.0.0.0:4000"
        volumes:
            - .:/code
        container_name: backend
        depends_on:
            - db
        network_mode: service:db
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            POSTGRES_HOST: db
            DJANGO_SUPERUSER_USERNAME: root
            DJANGO_SUPERUSER_PASSWORD: password

    frontend:
        restart: always
        build:
            context: frontend
            dockerfile: Dockerfile
        container_name: frontend
        working_dir: /app/frontend
        command: npm run dev
        ports:
            - "3000:3000"

    db:
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
            - "4000:4000"
        volumes:
            # - postgres_data:/var/lib/postgresql/data
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            # POSTGRES_HOST_AUTH_METHOD: trust

volumes:
    postgres_data: