version: "3.9"

services:
    django:
        build:
            context: backend
            dockerfile: Dockerfile
        working_dir: /code/backend/
        # command: sleep infinity
        command: >
            sh -c "python3 manage.py makemigrations 
            && python3 manage.py migrate 
            && python manage.py loaddata fixtures/initial_users 
            && python3 manage.py runserver 0.0.0.0:4000"
        volumes:
            - .:/code
        container_name: backend
        depends_on:
            - db

        ports:
            - "4000:4000"
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            POSTGRES_HOST: db
            DJANGO_SUPERUSER_USERNAME: root
            DJANGO_SUPERUSER_PASSWORD: password
            S3_HOST: http://s3ninja:9000/
            S3_BUCKET_NAME: media
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
            AWS_S3_REGION_NAME: us-east-1

    frontend:
        restart: always
        build:
            context: frontend
            dockerfile: Dockerfile
        container_name: frontend
        working_dir: /app/frontend
        volumes:
            - .:/app
            - /node_modules
            - /.next
        command: npm run dev
        ports:
            - "3000:3000"

    db:
        image: postgres:13
        restart: always
        ports:
            - "5432:5432"
            # - "4000:4000"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: django_postgres
            POSTGRES_PASSWORD: admin_password
            POSTGRES_NAME: django_db
            # POSTGRES_HOST_AUTH_METHOD: trust


    s3ninja:
        container_name: s3ninja
        image: scireum/s3-ninja:latest
        ports:
            - 9444:9000
        environment:
            storage.awsAccessKey: test
            storage.awsSecretKey: test
            storage.autocreateBuckets: 1
        volumes:
            - s3ninja_data:/home/sirius/data/

volumes:
    postgres_data:
    s3ninja_data:
