# Generated by Django 5.0.3 on 2024-04-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MenuItemPosition',
        ),
    ]
