# Generated by Django 5.0.3 on 2024-03-24 00:29

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=menu.models.upload_path),
        ),
    ]
